config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :user_favorites
  resources :designers
  resources :events
  resources :user_events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :content, presence: true
  validate :check_length

  def user_name
    user.name
  end

  def check_length
    if !content.nil? && content.length > 250
      errors.add(:content, "Comment cannot be greater than 250 characters in length!")
    end
  end


end

app/models/designer.rb
class Designer < ApplicationRecord
    has_many :events
    has_many :user_favorites
    has_many :users, through: :user_favorites

def self.search(term)
      if term
        where('name LIKE ?', "%#{term}%").order('id DESC')
      else
        order('id DESC')
      end
    end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :users, through: :user_events
  belongs_to :designer
  has_many :comments

  def self.search(term)
        if term
          where('title LIKE ?', "%#{term}%").order('id DESC')
        else
          order('id DESC')
        end
  end




end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_events
  has_many :events, through: :user_events
  has_many :user_favorites
  has_many :designers, through: :user_favorites
  has_many :comments

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true

end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :designer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment = Comment.new comment_params
    if !@comment.save
      flash[:message] = @comment.errors.full_messages.first
    end
    redirect_to events_path

  end



  private



    def comment_params
      params.require(:comment).permit(:content,:user_id,:event_id)
    end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :find_designer, only:[:show, :edit]


 def index
  # @designers = Designer.all
    @designers = Designer.all
    @designers = Designer.search(params[:term])


 end


 def show

 end

 # def new
 #   @designer = Designer.new
 #
 # end

 def create

   @designer = Designer.create(designer_params)

   redirect_to designers_path
 end

 def edit

 end



private

 def find_designer
   @designer = Designer.find(params[:id])
 end

 def designer_params
   params.require(:designer).permit(:name, :style)
 end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only:[:show, :edit]

 def index

    @events = Event.all
    @events = Event.search(params[:term])

 end


 def show

 end

 def new
   @event = Event.new

 end

 def create

   @event = Event.create(event_params)

   redirect_to events_path
 end

 def edit

 end

 

private

 def find_event
   @event = Event.find(params[:id])
 end

 def event_params
   params.require(:event).permit(:title, :description, :location, :time, :designer_id)
 end

end

app/controllers/user_events_controller.rb
class UserEventEventsController < ApplicationController
  before_action :find_user_event, only:[:show, :edit]

 def index
  # @usereventevents = UserEvent.all
    @user_events = UserEvent.all

 end


 def show

 end

 # def new
 #   @userevent = UserEvent.new
 #
 # end

 def create

   @user_event = UserEvent.create(user_event_params)

   redirect_to user_events_path
 end

 def edit

 end



private

 def find_user_event
   @user_event = UserEvent.find(params[:id])
 end

 def user_event_params
   params.require(:user_event).permit(:user_id, :event_id)
 end

end

app/controllers/user_favorites_controller.rb
class UserFavoriteFavoritesController < ApplicationController
  before_action :find_user_favorite, only:[:show, :edit]

 def index
  # @userfavorites = UserFavorite.all
    @user_favorites = UserFavorite.all

 end


 def show

 end

 # def new
 #   @userfavorite = UserFavorite.new
 #
 # end

 def create

   @user_favorite = UserFavorite.create(user_favorite_params)

   redirect_to user_favorites_path
 end

 def edit

 end



private

 def find_user_favorite
   @user_favorite = UserFavorite.find(params[:id])
 end

 def user_favorite_params
   params.require(:user_favorite).permit(:user_id, :designer_id)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only:[:show, :edit]

 def index
  # @users = User.all
    @user = User.new
  #  @designers = Designer.all


 end


 def show

 end

 # def new
 #   @user = User.new
 #
 # end

 def create


   @user = User.create(user_params)
   if @user.valid?
     redirect_to designers_path(@designers)
   else
     flash[:errors] = @user.errors.full_messages
     redirect_to users_path
   end

 end

 def edit

 end



private

 def find_user
   @user = User.find(params[:id])
 end

 def user_params
   params.require(:user).permit(:name, :email, :password)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/helpers/user_favorites_helper.rb
module UserFavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="demian">
<h1 class="subtitle">Add a comment:</h1></div>

<% if flash[:messages] %>
  <p class="error-message"> <%= flash[:message] %></p>
<% end %>

<%= form_tag '/comments', method:'post' do %>
  <%= text_area_tag 'comment[content]', nil, class:"field comment-box" %><br>

  <input type="hidden" name="comment[user_id]" value="<%= session[:user_id] %>">
  <input type="hidden" name="comment[phrase_id]" value="<%= params[:id] %>">
  <%= submit_tag "Create Comment", class:"button-text submit-button" %>
<% end %>

app/views/designers/index.html.erb
<div class="arturo">


<div class="container">
  <div class="row">
    <div class="color-d2">
    <h1 class="color-designer-name"> DESIGNERS</h1>
    </div>
    <img src=http://www.marwaricollegeranchi.com/images/fdimages/fdmain.gif>
    <img src=http://worlduniversityofdesign.ac.in/assets/images/bgs/fd2.jpg>
  </div>
</div>
</div>

<div class="container">

<%= form_tag(designers_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil, :class =>'btn btn-primary' %>
<% end %>

<div class="color-d1">


<% @designers.each do |designer| %>
  <div><li><%= link_to designer.name, designer_path(designer) %></li></div>
<% end %>
</div>
</div>

app/views/designers/show.html.erb
<div class="Ralph">
  <h1 class="lauren"><%= @designer.name %></h1>
</div>


<img src= <%= @designer.img_url %> class="rounded mx-auto d-block">
<div class="arturo">

<h4>Style:</h4><%= @designer.style %>
</div>

<% @designer.events.each do |event|  %>
    <h2>Title:</h2><%=  event.title   %>
    <br></br>
    <h2>Description:</h2>  <%=  event.description%>
    <br></br>
    <h2>Location:</h2>    <%= event.location %>
    <br></br>
    <h2>Time:</h2>    <%= event.time %>

<% end %>
<%= button_to "Events of this designer", events_path, method: :get, :class =>'btn btn-primary' %>

app/views/events/index.html.erb
<div class="even1">
<h1 class="event2">EVENTS</h1>
</div>

<div class="color-d1">
<% @events.each do |event| %>
  <div><li> <%= link_to event.title, event_path(event) %> </li></div>
<% end %>
</div>

<%= form_tag(events_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil, :class =>'btn btn-primary' %>
<% end %>

<div class="col">

<img src=http://www.pacificterrace.com/resourcefiles/blogsmallimages/kris-atomic-73935_1-337614.jpg class="img-thumbnail">
<img src= https://bizbash-production.imgix.net/content/editorial/storyimg/big/_dsc0424-copy-copie.jpg?auto=format class="rounded mx-auto d-block">

</div>

app/views/events/show.html.erb
<div class="even1">
  <h1 class="event2"><%= @event.title %></h1>
</div>

<img src= <%= @event.img_url %> class="rounded mx-auto d-block">
<div class="des2">


<h2>Description:</h2><p><%= @event.description %></p>
<h2>Location:</h2><p><%= @event.location %></p>
<h2>Time:</h2><p><%= @event.time %></p>
</div>

<%= button_to "Give a comment", new_comment_path, method: :get, :class =>'btn btn-primary' %></div>

app/views/users/_form.html.erb
<ol>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  <% end %>
</ol>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="rounded mx-auto d-block">
      <div class="welcome">
    <h1 class="color-h1">WELCOME TO STYLY </h1>
      </div>
      </div>
  </div>
</div>
<div class="container2">
  <div class="container">
<div class="form-group">
  <h3>Sign up to get info on the latest samples sales.</h3>
  <%= render partial: 'form' %>
  <%= form_for @user do |f| %>
    <%= f.label :Username %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit 'Create user', :class =>'btn btn-primary' %>
  <% end %>
</div>
</div>
</div>

<div class="container">
  <div class="row">
    <img src=http://nidmag.com/steam/dynamic/W1siZmYiLCIvdmFyL3d3dy9jYXJkZmxpcC9wdWJsaWMvc2l0ZXMvNThjOGMwYmUyNTY3YTU4NTNjMWY0YTdjL2NvbnRlbnRfZW50cnk1OGNiZjJlMjI1NjdhNTI5YTZmODdiZGMvNThjYmY2YzAyNTY3YTUyOWE2Zjg3ZmY1L2ZpbGVzL0NvdXJ0ZXN5X29mX0Nhc2V5X0tlbGJhdWdoX1RoZV9OZXdfWW9ya19UaW1lcy5qcGciXSxbInAiLCJ0aHVtYiIsIjExNDB4NzAwIyJdXQ/fa4956b7f091050e/Courtesy_of_Casey_Kelbaugh_The_New_York_Times.jpg class="img-thumbnail">

  </div>
</div>